if game:GetService("Workspace").Teleporters then game:GetService("Workspace").Teleporters:Destroy() end 
getgenv().autoDunk = true
function autoDunker()
		while autoDunk do
				game.Players.LocalPlayer.Character.Humanoid.WalkSpeed = 100
				game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = game:GetService("Workspace").BlueGoal1.Score.CFrame + Vector3.new(100,-10,0)
                -- game.Players.LocalPlayer.Character.HumanoidRootPart.Anchored = true
                wait(1)         
                game:GetService("Players").LocalPlayer.Character.Ball.ServerEvent:FireServer("Accuracy", 1)
                game:GetService("Players").LocalPlayer.Character.Ball.ServerEvent:FireServer("Start")
                wait(2)
                for i=1,10 do
                    game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = game:GetService("Workspace").BlueGoal1.Score.CFrame + Vector3.new(0,-1,0)
                    wait(0.1)
                end
		end
end
autoDunker()

-- Script generated by SimpleSpy - credits to exx#9394
-- upgrade the dunk (cash multiplier)
local args = {
    [1] = "Dunk"
}

game:GetService("ReplicatedStorage").ServerEvent:FireServer(unpack(args))

-- Script generated by SimpleSpy - credits to exx#9394
-- upgrade next rebirth
local args = {
    [1] = "Rebirth"
}

game:GetService("ReplicatedStorage").ServerEvent:FireServer(unpack(args))

-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = "Buy",
    [2] = "Jerseys",
    [3] = "Classic"
}

game:GetService("ReplicatedStorage").ServerEvent:FireServer(unpack(args))

-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = "Buy",
    [2] = "Jerseys",
    [3] = "Abstract"
}

game:GetService("ReplicatedStorage").ServerEvent:FireServer(unpack(args))

-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = "Buy",
    [2] = "Balls",
    [3] = "Grass"
}

game:GetService("ReplicatedStorage").ServerEvent:FireServer(unpack(args))


-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = "Join"
}

game:GetService("ReplicatedStorage").Contest.RemoteEvent:FireServer(unpack(args))
